### ISSUE TITLE
Error handling for gaps in data during FITS CSV creation

### ISSUE THREAD

**Issue by emkaser** [uga-libraries/accessioning-scripts#35]
**Location:** format_analysis_functions.py, make_fits_csv()

**Description:** format_analysis.py script stops and throws a TypeError when it hits a NoneType object while creating the FITS CSV. This has happened on two different accessions, both of which were unusually large (100s of GB). 

Example of error message:
```
Traceback (most recent call last):
  File "F:\scripts\accessioning-scripts-main\format_analysis.py", line 72, in <module>
    make_fits_csv(fits_output, accession_folder, collection_folder, accession_number)
  File "F:\scripts\accessioning-scripts-main\format_analysis_functions.py", line 281, in make_fits_csv
    rows_list = fits_row(f"{accession_folder}_FITS/{fits_xml}")
  File "F:\scripts\accessioning-scripts-main\format_analysis_functions.py", line 174, in fits_row
    format_data = {"name": identity.get("format"), "version": get_text(identity, "version")}
  File "F:\scripts\accessioning-scripts-main\format_analysis_functions.py", line 140, in get_text
    value += item.text
TypeError: can only concatenate str (not "NoneType") to str
```

**Ideas:** It would be helpful to be able to see that this error has occurred and identify the FITS file that is triggering the TypeError, without stopping the script entirely. Maybe error handling could print a warning to the terminal (and log the NoneType issue in the FITS CSV as NULL data, or something else?) while allowing the script to continue.

**Comment by emkaser** [comment]
Initial testing on a problem accession shows a NoneType object appearing in the "FITS_Format_Version" field. Replacing that object with the string "ERROR" allows the script to finish. All other FITS fields for that file are filled as normal.

**Comment by amhanson9** [comment]
Determined the error is from empty elements and want to skip the value rather than have a string to indicate an error. Updated get_text() to leave value of None if element is empty. Added error handling to fits_row() to work if version is None, which causes a TypeError when calculating the dictionary key for dealing with multiple format identifications of the same file.

**Comment by amhanson9** [comment]
@emkaser this is ready for testing.
